version: "3"
services:
  app:
    build: docker
    ports:
      - 80:80
    command: /bin/sh -c "/usr/local/sbin/php-fpm --allow-to-run-as-root & /usr/sbin/nginx -g 'daemon off;'"
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_KEY: "base64:t+VMAZzL3stMlHCUG1G8hGJV3gZSm7c4k+iFVsna+QI="
    links:
      - mysql
  node:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
      - /var/www/html/node_modules
    command: /bin/sh -c "yarn install && yarn watch-poll"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
      MYSQL_USER: playground
      MYSQL_PASSWORD: playground
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.data:/var/lib/mysql:delegated
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:delegated
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:delegated
    ports:
      - 3306:3306
